# Generated by Django 4.2 on 2023-05-14 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier', models.CharField(blank=True, max_length=200, null=True)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=25, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField(default=datetime.datetime.now)),
                ('device_created_date', models.DateTimeField(auto_now_add=True)),
                ('device_updated_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='static/reports/store/device_reports/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/images/store/device_photos/')),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('grade', models.CharField(blank=True, max_length=25, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_department', to='store.department')),
                ('device_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DeviceDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(max_length=50, unique=True)),
                ('defect_description', models.TextField(blank=True, max_length=500, null=True)),
                ('defect_solution', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Device Defect',
                'verbose_name_plural': 'Device Defects',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WorkOrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('purchase', 'Purchase'), ('return', 'Return')], default='repair', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkOrderCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.workordercart')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_defects',
            field=models.ManyToManyField(default=None, help_text='Select all that apply', related_name='device_defects', to='store.devicedefect'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.location'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
